apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: guestbook
  description: guestbook
  annotations:
    # mandatory annotation
    harness.io/project-url: https://app.harness.io/ng/#/account/BKB_Vic2RbWnsMSUAWTgXw/home/orgs/default/projects/GitOps/details
    # optional annotations, don't include this block if not needed. Add this if specific pipeline executions needs to be shown on the Plugin. When specified, latest pipeline execution details for configured pipelineIds(max 10) and configured serviceId will be shown.
    harness.io/ci-pipelineIds: guestbook
    harness.io/cd-serviceId: guestbook
  tags:
    - guestbook
    - gitops
    - applicationset

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://app.harness.io/ng/#/account/BKB_Vic2RbWnsMSUAWTgXw/home/orgs/default/projects/GitOps/details
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
spec:
  type: service
  lifecycle: Production
  owner: Martin Ansong
